### ISSUE TITLE
utools自动隐藏

### ISSUE THREAD

**Issue by fecet** [gxt-kt/dwm#2]
我习惯使用utools来作为程序的启动器，但utools默认会在焦点丢失的时候自动隐藏，这会跟dwm产生奇怪的互动，导致utools在删除字符时会自动隐藏。我不熟悉dwm的源代码实现，不知道如何解决，希望作者指点一二

**Comment by gogongxt** [comment]
不好意思，我不用utools，不太了解这个问题，类似软件rofi或者klaunch我都是可以正常使用的。
我建议你首先关闭picom等动效。
然后使用以下两种进行对比：
1. 使用原生的dwm，复现一下类似问题，这样可以知道是否为我修改代码导致的bug。
2. 使用i3wm或者bspwn等平铺式桌面，复现一下类似问题，这样可以确认是否是dwm窗口聚焦的问题。

复现结果和我说下，我就应该可以定位问题所在了。

**Comment by fecet** [comment]
做了一些测试, 主要问题是会在删除完最后一个字符的时候隐藏:

- 使用yaoccc的配置, 一定会出现这个问题
- 使用这个配置:
  - 只使用一个屏幕(或者镜像), 工作正常
  - 在两个屏幕下, 一个tag内没有活动窗口时打开, 工作正常
  - 有活动窗口时打开utool, 会出现这个问题
  - 如果有两个窗口, 先进行一些focusstack操作后再打开utool, 工作正常
  - 在上一条的条件下, 再删去这个tag下的其他活动窗口, 问题不会再出现

https://github.com/gxt-kt/dwm/assets/41792945/503bae81-e5d8-48ee-9fe1-ad93b5f6bfc0

**Comment by gogongxt** [comment]
我大概懂了bug复现条件，按照现在的复现条件我更倾向于认为是utools的bug。

如果可以的话，建议还是先关闭picom再试一下，picom对窗口一些逻辑影响还是挺大的。

另外可以用原生的dwm复现一下，如果还存在那就无解了。

**Comment by fecet** [comment]
关闭picom和原生dwm都试了, 结果差不多.
肯定是utools自己的bug, 但我猜测是utools对平铺管理器的支持不太行, 因为网上没搜到类似的问题, 我猜在gnome kde上面应该没啥问题, 所以想看看能不能通过修改dwm设置把这个解决了

**Comment by gogongxt** [comment]
我估计自己修改代码解决utools的bug有点困难，主要是删除最后一个字符并关闭窗口这个过程dwm是没法控制和接管的。

建议还是和utools官方反馈一下（不过估计他们也并不打算针对平铺式桌面做优化）

可以试试使用rofi或者klaunch平替，也是很好用的。

**Comment by fecet** [comment]
用rofi和klauch做启动器肯定比utools强, 就是utools有些插件生态, 虽然我也不常用, 不过还是懒得换了, 唉

**Comment by ElvinChan777** [comment]
> 用rofi和klauch做启动器肯定比utools强, 就是utools有些插件生态, 虽然我也不常用, 不过还是懒得换了, 唉
兄弟我用的和你一样的配置，但是我没出现删除最后一个字符隐藏的问题，倒是打开词典会自动隐藏
