### ISSUE TITLE
腾讯会议共享时全局灰色蒙版

### ISSUE THREAD

**Issue by fecet** [gxt-kt/dwm#3]
不知道您用不用腾讯会议, 配置文件里好像没怎么对它特别设置. 
目前使用最新版本的腾讯会议, 共享时会出现一个这样的蒙版
![image](https://github.com/gxt-kt/dwm/assets/41792945/2b663023-4cd2-4a3b-bc46-c6629e0576ff)
这里直接用这里的图了
https://bbs.archlinuxcn.org/viewtopic.php?id=12542
虽然关闭picom可以解决, 不过想看看有没有更好的办法. 

还有开会的时候把窗口聚焦的时候会出现一个叫做"EmojiFloatWnd"的窗口, 鼠标移开就会消失, 非常烦人.
当然这可能也是wemeet本身的问题...

**Comment by gogongxt** [comment]
我用腾讯会议的，几个月前测试的时候确实是有很多问题，不过主要还是腾讯会议自身的问题。

蒙版问题需要在picom配置文件里设置，加入规则类似于
` "class_g *= 'wemeetapp'"`，把一些模糊还是透明的东西让wemeetapp排除掉。
比如透明度设置：
```
opacity-rule = [
"100:class_g = 'wemeetapp'",
];
```

聚焦窗口问题暂时没有好的解决方法，主要还是腾讯会议对平铺式桌面支持不太友好，我使用i3wm也会碰到和dwm一样的问题。

另外其实这种带悬浮式窗口的和平铺式桌面或多或少都有不友好的地方，只能说能用，体验肯定都不会很好。

**Comment by gogongxt** [comment]
关于picom配置文件可以参考：
https://github.com/gxt-kt/dotfiles/blob/d1059b9d3215df5b63c0c08a6dc5021ab51e494d/picom/.config/picom/picom.conf

**Comment by fecet** [comment]
想问一下聚焦的问题为什么会这么棘手啊, 我尝试在配置里设置
```
    {"EmojiFloatWnd",          NULL,       NULL,  TAGMASK,     1,         0,        1,        -1},  // 
```
不过好像没起作用, 那个窗口还是平铺展开了

**Comment by gogongxt** [comment]
你这里设置的是class，你确定那个窗口类型是EmojiFloatWnd吗？你这里想设置的应该是title吧。
关于查看一个窗口的class和title可以使用x11的`xprop`命令。

**Comment by fecet** [comment]
确实..注释看叉了
